### ISSUE TITLE
core: frontend: Lazy-load notifications

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#524]
Notifications list is currently not lazy-loaded. Because of this, if there are too many notifications, the menu becomes lag as hell, sometimes not even opening.

DAYS_TO_DEVELOP:1

**Comment by patrickelectric** [comment]
@rafaellehmkuhl it was fixed by #608, right ?

**Comment by rafaellehmkuhl** [comment]
> @rafaellehmkuhl it was fixed by #608, right ?

Not yet. #608 reduced the number of notifications, but they are still not lazy loaded.

**Comment by rafaellehmkuhl** [comment]
With #791 this is no longer a problem. Closing as a non-issue.
